### ISSUE TITLE
bug: segmentation fault

### ISSUE THREAD

**Issue by 7flash** [webui-dev/deno-webui#20]
reproduce: 

1) save minimal code example https://github.com/webui-dev/webui/issues/231#issuecomment-1732844452

```
import { WebUI } from "./deno-webui/mod.ts";

const firstWindow = new WebUI();

let taskId = 0;
firstWindow.bind('saveScene', () => {
  taskId++;
  (async () => {
    await new Promise(resolve => setTimeout(resolve, 100));
    firstWindow.script(`alert('${taskId} completed at ${new Date().toLocaleTimeString()}')`);
  })();
  return { taskId };
});

try {
  await firstWindow.show(`<html>${new Date().toLocaleTimeString()}<script src="/webui.js"></script></html>`);
} catch (err) {
  console.error(err);
}

await WebUI.wait();
```

2) 
```
deno run --allow-all --unstable main.ts
```

3) Open devtools and run
```
window.webui.call('saveScene', '')
```

4) alert window will appear as expected

5) run the same command again
```
window.webui.call('saveScene', '')
```

6) unfortunatley, app will be closed with error in terminal: segmentation fault

**Comment by 7flash** [comment]
So no more webui.call ? All bindings are directly attached to window?

**Comment by 7flash** [comment]
Also can I do await myBackend() ?

**Comment by ttytm** [comment]
> So no more webui.call ? All bindings are directly attached to window?

`webui.call` is still possible.
 
If the function is globally available it's directly attached to the window. You cann also call it via the `webui` object. E.g., `webui.my_backend_func`.

Here is a reference to a discussion regarding this feature impelmentation: https://github.com/webui-dev/webui/discussions/263#discussioncomment-7411967

**Comment by 7flash** [comment]
Thanks this issue seem to be solved, it reads the arguments, but still doesn't work with async functions: https://github.com/webui-dev/deno-webui/issues/22

**Comment by 7flash** [comment]
Apparently this issue was happening because of error in my code described above and since it was not properly handled it was leading to crash; but now I noticed this error also appear spontaneously when I don't execute any functions, that we can debug in separate issue https://github.com/webui-dev/deno-webui/issues/24
