### ISSUE TITLE
bug: script result limited to 8191 symbols

### ISSUE THREAD

**Issue by 7flash** [webui-dev/deno-webui#23]

**Comment by 7flash** [comment]
When I run this script in dev tools,

```
window.webui.executeDeno(`
              async function saveScene() {
const bit = await firstWindow.script("return 'x'.repeat(10000);");
console.log(bit.length);
} `)
```

I am expecting to see 10000 in console but unfortunately it shows 8191

**Comment by 7flash** [comment]
Sorry just noticed the solution to pass bufferSize in options

https://github.com/webui-dev/deno-webui/blob/d48f8a3df0ce2185885c778f3d84489b44f84e2b/src/webui.ts#L235

Perhaps its possible to increase or remove default limit?

**Comment by ttytm** [comment]
The default limit is 8 KiB. Custom sizes to reduce or increase the default value can be passed via the options arg. 

https://github.com/webui-dev/deno-webui/blob/d48f8a3df0ce2185885c778f3d84489b44f84e2b/src/webui.ts#L225-L230

**Comment by 7flash** [comment]
I think better solution would be to automatically calculate buffer length, currently I have to do manually in two steps:

```
            const bufferSize = await firstWindow.script('return window.ea.getFiles()["' + fileId + '"].dataURL.length;');
      var fileDataURL = await firstWindow.script('return window.ea.getFiles()["' + fileId + '"].dataURL;', {
              bufferSize: bufferSize + 1,
            });
```

The issue that I have to re-executed same code twice, it would be better if it can automatically cache first result and then return with correct bufferSize

**Comment by ttytm** [comment]
Enough memory needs to be allocated to hold the response. How should it be calculated before there is a response? The only way would be raising it but it comes with a trade off. 8KiB is enough to hold most responses but it was kept configurable. If a higher limit is needed why not just passing the buffersize arg right away?

**Comment by 7flash** [comment]
I mean something like this 

```
const bufferSize = await firstWindow.script('const result = expensiveComputation(); window.cache = result; return result.length; ');
const result = await firstWindow.script('return cache;', {
              bufferSize: bufferSize + 1,
            });
```

Though it's not important issue, just an idea

**Comment by ttytm** [comment]
It would be stored in the cache field of the window object. JS has a GC and doesn't need to allocate memory manually like we need in C with the buffer. While this is possible, I think it's not worth the tradeoff in performance to make it the default behavior. Maybe there can be some api that provides this behaviour to spare the boilerplate for users who run into cases like @7flash does.

**Comment by AlbertShown** [comment]
Or, because webui runs on PCs, why not make the default buffer 1MB or even more?

**Comment by 7flash** [comment]
@ttytm what's the proper way to calculate buffer size of string? just .length might not be right?

**Comment by 7flash** [comment]
> @ttytm what's the proper way to calculate buffer size of string? just .length might not be right?

currently doing like this but on other hand it might be over head:

bufferSize *= 4;
bufferSize += 4;

**Comment by ttytm** [comment]
I'm not fully sure. @hassandraga can you tell the correct way for WebUI?

**Comment by hassandraga** [comment]
> what's the proper way to calculate buffer size of string?

`const bufferSize = Buffer.byteLength(str, 'utf-8');` is the right one to get the size of a buffer in bytes, while `.length` gives the string len. To see the difference, use a Unicode text.

```js
const str = "السلام عليكم"; // Hello in Arabic
console.log(str.length); // 12
console.log(Buffer.byteLength(str, 'utf-8')); // 23
```

**Comment by 7flash** [comment]
> > what's the proper way to calculate buffer size of string?
> 
> `const bufferSize = Buffer.byteLength(str, 'utf-8');` is the right one to get the size of a buffer in bytes, while `.length` gives the string len. To see the difference, use a Unicode text.
> 
> ```js
> const str = "السلام عليكم"; // Hello in Arabic
> console.log(str.length); // 12
> console.log(Buffer.byteLength(str, 'utf-8')); // 23
> ```

Uhm but Buffer is not available in browser and that's whole point to measure it in browser

**Comment by hassandraga** [comment]
That's true. But the example was just to show the difference between characters length, and bytes length. However  in the browser you can encode the string, then get length, which will give the bytes length, and that what we used in WebUI Bridge.

`new TextEncoder().encode(str).length`

**Comment by 7flash** [comment]
> That's true. But the example was just to show the difference between characters length, and bytes length. However in the browser you can encode the string, then get length, which will give the bytes length, and that what we used in WebUI Bridge.
> 
> `new TextEncoder().encode(str).length`

Unfortunately that's expensive operation which does not work with long strings as shown in https://github.com/webui-dev/webui/issues/270 and later fixed with chunking in https://github.com/webui-dev/webui/pull/271 but it would be too expensive I think just to calculate bytes length, and rather I will just reserve a bit more bytes, do you think it will always work just to multiple str len by two?
