### ISSUE TITLE
deno example not work: "call a backend function from deno"

### ISSUE THREAD

**Issue by tvortsa** [webui-dev/deno-webui#44]
this example: https://webui.me/docs/2.4/#/?id=call-a-backend-function-from-javascript

is not work for me

`response` is `undefined`, not "Message from JS" 

` ui send "undefined" `

**Comment by renatoathaydes** [comment]
I think OP means this example:

```typescript
webui.bind("MyID", ({ data }) => {
  console.log(`ui send "${data}"`);
  return "backend response";
});
```
This doesn't work becasue the callback arg is of type `WebUi.Event`.

Hence, the example should read:

```
myWindow.bind('MyID', (e: WebUI.Event) => {
  console.log(`ui send "${e.arg.number(0)}"`);
  return "backend response";
});
```
As far as I can see, one must know the type of the argument, which is why `e.arg.number(argIndex)` or `e.arg.string(argIndex)` or `e.arg.boolean(argIndex)` must be used?!

BTW Are only `string | number | boolean` supported as arguments??

**Comment by tvortsa** [comment]
Thanks everyone for the answers!

I don’t have any problems with argument types, because I don’t write in Typescript (never...  **N-E-V-E-R-R-R-R-R !!!**)

My problem was that the bind did not have time to happen. The solution to my problem is webui.setEventCallback()

It seems to me that this should be placed in the main documentation and examples and separately mentioned that nothing will work for you, simply because you will call a `webui ` that does not exist at the time of the call!

For less experienced developers, this is a very important point!

So it is my salvation code:

![image](https://github.com/webui-dev/deno-webui/assets/78345/4462a5fd-5776-41d4-8156-179c2664ee50)

**Comment by tvortsa** [comment]
> Does [hello world](https://github.com/webui-dev/deno-webui/blob/main/examples/hello_world/hello_world.ts) works fine for you?

Yes, this example works great and it’s rather discouraging, because the code in it is contained in <script> tags, and in any real project your code is always included as an external file and the problem arises in the sequence of actions, you call webui before it has time to load and that's why everything doesn't work.

I have already found a solution here in the discussions of this repository: `webui.setEvemtCallback()` but it would be great if it were included in the documentation and not hidden in the jungle of discussions, requiring you to find yourself first, getting nervous and perhaps deciding that webui is not very working crap at all
