### ISSUE TITLE
bug: 🐍 error on library decoding

### ISSUE THREAD

**Issue by JOTSR** [webui-dev/deno-webui#5]
# Issue
Error on executing module without `--allow-all` flag.
(try to repoduce the bug on different plateform)

# Context
The lib files are cached before runtime with static imports in "./deps.ts" via [ejm.sh](https://ejm.sh). As ejm.sh serves b64 encoded string of the binary data and `Deno.dlopen` only accepts filesystem path the method is to use the cached base64 string, decode  it and write it to a file in the user temp directory and use it as `Deno.dlopen` path.

# Description
Seems to only fails on windows.
When trying to run the module with the smallest restrictions (`deno run --allow-read --allow-write --allow-ffi --unstable "...WEBUI" `).

```sh
error: Uncaught (in promise) NotFound: Le specified filed was not found. (os error 3): writefile 'C:\Temp\webui-2-x64.dll'
    Deno.writeFileSync(libPath, libBuffer);
         ^
    at Object.writeFileSync (ext:deno_fs/30_fs.js:771:7)
    at writeLib (file:///.../deno-webui/src/utils.ts:31:10)
    at loadLib (file:///.../deno-webui/src/lib.ts:34:34)
    at new WebUi (file:///.../deno-webui/src/webui.ts:54:47)
    at file:///.../deno-webui/examples/file_explorer/main.tsx:7:16
    at eventLoopTick (ext:core/01_core.js:183:11)
```

But works fine with (`deno run -A --unstable "...WEBUI" `), note that no other permissions are requested.
Need to be investigate. Maybe an error due to "os_paths" dependency or from Deno runtime, in that case need to report the issue.

**Comment by AlbertShown** [comment]
What `-A` does?
And does the file `C:\Temp\webui-2-x64.dll` exist?

**Comment by JOTSR** [comment]
`-A`stands for `--allow-all`.  The issue came maybe from [os_paths](https://deno.land/x/os_paths) used to write cache to the temp file of the user (only give the temp user path depending of the os).

Normally it should return `C:/Users/<username>/AppData/Local/Temp` on windows but it don't work properly without `--allow-all` flag, so maybe a permission issue but no one ask. I don't known the situation on other os.

Some investigation is needed but a good hot fix can be to use `Deno.makeTempFile` instead.
I don't use it at first because as the name of the file is random I can't reuse the uncompressed lib between launchs but the startup time is not really impacted as the lib is already cached as base64 in ram at the script execution (and in deno cache disk cache between runs) due to `import ... 'https://esm.sh/...` .
