### ISSUE TITLE
latest webui build

### ISSUE THREAD

**Issue by sensiblearts** [webui-dev/deno-webui#51]
@hassandraga , that infinite reload issue https://github.com/webui-dev/webui/issues/392 when using SvelteKit is happening with deno-webui; both on Windows and Ubuntu (WSL).

If you guide me on what to do (or learn), I can try to update this repository to pull in the latest webui builds.

( FYI, I'm looking at Deno and Zig, to compare them for how effectively I can integrate a pouchdb API into my backend: https://github.com/pouchdb/pouchdb-server . I was thinking of spawning a process with Zig, but I just read that Deno might actually run this node/express code. )

**Comment by sensiblearts** [comment]
Moving the dll solved it.

And I can see the debug output now. (Yesterday with Zig, it wasn't for some reason; though my changes to the bridge were visible in JS console logs. Weird.)

**Comment by sensiblearts** [comment]
@hassandraga I had a bunch of stuff commented out in `webui_bridge.ts` so I did another check with the latest build (as of 9PM EST) of webui to confirm our earlier findings. I found something interesting:

With `Deno`, I _do not_ have to use `WebUI.bind("", handleEvent);` for my SvelteKit app to run without the infinite reload. I only have to do two things:
1. Use an html string (not a filename) as `file_content` when calling `webui.show(file_content)`, and
2. Change line 43 in `webui_bridge.ts` to `#allowNavigation = true;`

However, with `Zig`, I need both of the above plus:
3. Bind all events to a handler, e.g., ` _ = nwin.bind("", events);`

Strange.

(I have a feeling that this is related to multithreading. Just intuition.)

**Comment by sensiblearts** [comment]
OK. Are you testing it with a compiled SvelteKit SPA?

**Comment by sensiblearts** [comment]
I just downloaded `https://github.com/ttytm/gsysmo` and followed the "Quick Start" instructions and built it: It still has the infinite reload problem on my machine, Windows 10.

But the `go.mod` file is listing
```
github.com/webui-dev/go-webui/v2 v2.4.2-1.0
```
so I think I need to upgrade to the latest `go-webui`.

_Could you send me instructions on how to tell `Go` to get the latest?_

I tried the recursive git clone of `go-webui` and tried to figure out how to point `gsysmo`'s go.mod to a local path, but it won't build.

**Comment by ttytm** [comment]
Hey @sensiblearts, there are rough edges in this development phase prior to the release.

I didn't updated the project since the recent fixes. 
Gonna do so very soon and clarify the setup so that there will be a working result after following its steps.
