### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by Errel2022** [webui-dev/deno-webui#6]
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/webui/mod.ts' does not provide an export named 'WebUI'
import { WebUI } from "https://deno.land/x/webui/mod.ts";

**Comment by AlbertShown** [comment]
We updated this repo, but the module in [deno.land](https://deno.land/x/webui@2.3.0/mod.ts) will be automatically updated when we create a new release.

@JOTSR Any idea how to solve this?

**Comment by JOTSR** [comment]
As the latest change have not been released deno.land don't update the module so you can directely import module from github (eg: https://raw.githubusercontent.com/webui-dev/deno-webui/main/mod.ts). Pin a commit to ensure stable module reference.

Latest commit will work correctly eg: `deno run -A --unstable https://raw.githubusercontent.com/webui-dev/deno-webui/50fc01e8588d7455d0ee390cda4f3558dfb26ad9/examples/file_explorer/main.tsx`. Next release will be here soon as main API changes was made.
