### ISSUE TITLE
WebUI Error: File not found (./webui-2-x64.dyn) or (/x/webui@2.3.0/src/webui-2-x64.dyn)

### ISSUE THREAD

**Issue by lino-levan** [webui-dev/deno-webui#9]
This may just be an issue with the latest version not being released on github. More likely, webui doesn't support ARM macs, which is really problematic.

Reproduction:
```bash
$ deno run -A --unstable https://deno.land/x/webui/examples/hello_world.ts
WebUI Error: File not found (./webui-2-x64.dyn) or (/x/webui@2.3.0/src/webui-2-x64.dyn)
```

Environment:
- M1 Macbook Air
- Deno v1.36.0

**Comment by hassandraga** [comment]
We decided to remove all the pre-built binaries from all WebUI repos. We are working on a new GitHub-Actions Workflow to automatically and safely build binaries for all platforms (_Including M1_) when a new stable release is available.

I guess for now, your best option is to build WebUI from source using any C compiler in your machine (No dependencies are needed).

```
git clone https://github.com/webui-dev/webui.git
cd webui/build
sh macos_build.sh
```

Then use `webui/build/macOS/Clang/webui-2-x64.dyn` (_Same as `webui/dist/Clang/webui-2-x64.dyn`_).

**Comment by hassandraga** [comment]
If you have any issue with the `macos_build.sh` script, then simply build WebUI manually, it's easy:

```
git clone https://github.com/webui-dev/webui.git
cd webui/build/macOS/Clang/
make
```

**Comment by jeff-hykin** [comment]
> git clone https://github.com/webui-dev/webui.git
> cd webui/build
> sh macos_build.sh

These commands don't work for me (there is no `macos_build.sh`, and running `bridge/build.sh` only produces a .h file, no dyn), and I still get the original error of WebUI Error: File not found.

Might want to consider opening this back up

**Comment by hassandraga** [comment]
Hey @jeff-hykin, `macos_build.sh` was for old version 2.3.x, and it get removed. Now the [main repo](https://github.com/webui-dev/webui) is on 2.4 Beta.

You can download the latest pre-compiled nightly Beta build here:
https://github.com/webui-dev/webui/releases/tag/nightly

However, the actual Deno repo uses an old Beta 2.4. You don't need to build anything, just clone the Deno repo and run it. If you get any issues, please feel free to open a new issue and share details and logs as possible.
